export { default as blackOutlined } from './black-outlined.svg';
export { default as black } from './black.png';
export { default as lessSpikyWhiteOutlined } from './less-spiky-white-outlined.svg';
export { default as spikyBlackOutlined } from './spiky-black-outlined.svg';
export { default as spikyBlack } from './spiky-black.svg';
export { default as spikyWhiteOutlined } from './spiky-white-outlined.svg';
export { default as surikenBlack } from './suriken-black.svg';
export { default as white } from './white.svg';
export { default as spikyWhite } from './spiky-white.svg';
